"""MSL emission for tile kernels (docs/gpu_tiles.md, Stage 1c).

Compiles ONE kernel function (a `fn k(pid: int, <buffers: Vec...>) -> ()`)
from its MIR into a Metal Shading Language kernel body, plus a
self-checking MLX harness for a Mac.  The container this compiler
develops in has no Metal, so the emitter is designed to be testable
anyway: the emitted body is deliberately **C++-compatible MSL** — control
flow is a block switch-machine (MSL has no goto), buffers are plain
pointers, and the only Metal-ism is `thread_position_in_grid`, which a
five-line shim provides — so the differential tests compile the emitted
body with clang++ and race it against the interpreter END TO END.  What
remains untested here is exactly the MLX binding and Metal address
spaces, which the generated harness self-checks on a Mac.

The kernel subset (out-of-subset input raises MslError with the reason;
never wrong code):

  * signature `fn k(pid: int, b1: Vec, b2: Vec, ...) -> ()` — parameter 0
    is the instance id, every other parameter is an int-element buffer;
  * int scalars and INT tiles only — Metal has no f64, so float kernels
    are rejected until the f32 increment (`Tile.zeros` builds float
    tiles: use `Tile.filled(r, c, 0)` in kernels);
  * the MASKED buffer forms only (`Tile.load_or` / `Tile.store_clipped`):
    device kernels cannot raise, so the strict forms are host-side;
  * tile ops: filled / arange / load_or / store_clipped / add / mul /
    scale / dot / sum / transpose / rows / cols; int binops; any control
    flow the language produces (the switch-machine handles the CFG);
  * literal tile shapes (same rule as the native backend's kinds).

Execution contract (documented, enforced by construction): buffer READS
see the launch-entry snapshot, WRITES land in fresh output buffers merged
by a written-mask — so an instance may read what it wrote only through
values it still holds in tiles, and kernels relying on cross-instance
read-after-write within one launch are outside the contract (they would
be racy on any real GPU; the sequential CPU reference would hide that).
The mask merge is what makes `store_clipped`'s partial writes correct
under MLX's const-input model.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Dict, List, Optional, Sequence, Set, Tuple

from .mir import MirFunc

_INT_BINOPS = {"+": "+", "-": "-", "*": "*", "/": "/", "%": "%",
               "==": "==", "!=": "!=", "<": "<", "<=": "<=",
               ">": ">", ">=": ">="}

_TILE_OPS = {"filled", "arange", "load_or", "store_clipped", "load_rows",
             "store_rows", "add", "mul", "scale", "dot", "sum",
             "transpose", "rows", "cols"}


class MslError(Exception):
    """The kernel is outside the emitting subset; the message says why."""


@dataclass
class MslKernel:
    """An emitted kernel: the body is one C++-compatible MSL fragment."""
    name: str
    pid_var: str
    in_bufs: List[str]           # every buffer param, in signature order
    out_bufs: List[str]          # the subset the kernel writes
    body: str                    # references <b>_in / <b>_out / <b>_wm / lens

    def cpp_wrapper(self) -> str:
        """A C++ translation unit that runs the body sequentially over the
        grid — the container-side differential harness (no Metal here)."""
        params = ["uint3 thread_position_in_grid"]
        params += [f"const long* {b}_in" for b in self.in_bufs]
        for b in self.out_bufs:
            params += [f"long* {b}_out", f"long* {b}_wm"]
        params += ["const long* lens"]
        return "\n".join([
            "// generated by metaxu emit_msl (C++ shim differential harness)",
            "#include <cstdint>",
            "#include <cstdio>",
            "#include <cstdlib>",
            "#include <vector>",
            "struct uint3 { unsigned x, y, z; };",
            "static_assert(sizeof(long) == 8, \"long must be 64-bit\");",
            f"static void kernel_body({', '.join(params)}) {{",
            self.body,
            "}",
            "",
            "// main: argv = grid_n, then per-buffer files are stdin-fed as",
            "// whitespace-separated ints: n_bufs, then len+elems per buffer.",
            "int main(int argc, char** argv) {",
            "    int grid_n = atoi(argv[1]);",
            "    int nb; if (scanf(\"%d\", &nb) != 1) return 2;",
            "    std::vector<std::vector<long>> bufs(nb);",
            "    std::vector<long> lens(nb);",
            "    for (int i = 0; i < nb; i++) {",
            "        long n; if (scanf(\"%ld\", &n) != 1) return 2;",
            "        lens[i] = n; bufs[i].resize(n);",
            "        for (long j = 0; j < n; j++)",
            "            if (scanf(\"%ld\", &bufs[i][j]) != 1) return 2;",
            "    }",
            "    // outputs + masks for the written buffers",
            "    std::vector<std::vector<long>> outs, wms;",
            "    for (size_t k = 0; k < " + str(len(self.out_bufs)) + "; k++)"
            " { outs.push_back({}); wms.push_back({}); }",
            *[f"    outs[{i}].assign(lens[{self.in_bufs.index(b)}], 0);\n"
              f"    wms[{i}].assign(lens[{self.in_bufs.index(b)}], 0);"
              for i, b in enumerate(self.out_bufs)],
            "    for (int pid = 0; pid < grid_n; pid++) {",
            "        uint3 tpg{(unsigned)pid, 0, 0};",
            "        kernel_body(tpg"
            + "".join(f", bufs[{self.in_bufs.index(b)}].data()"
                      for b in self.in_bufs)
            + "".join(f", outs[{i}].data(), wms[{i}].data()"
                      for i in range(len(self.out_bufs)))
            + ", lens.data());",
            "    }",
            "    // merge: written elements from out, the rest from input",
            *[f"    for (long j = 0; j < lens[{self.in_bufs.index(b)}]; j++)"
              f" if (!wms[{i}][j])"
              f" outs[{i}][j] = bufs[{self.in_bufs.index(b)}][j];"
              for i, b in enumerate(self.out_bufs)],
            "    for (size_t k = 0; k < outs.size(); k++) {",
            "        for (size_t j = 0; j < outs[k].size(); j++)",
            "            printf(\"%ld\\n\", outs[k][j]);",
            "    }",
            "    return 0;",
            "}",
        ])

    def mlx_harness(self, grid_n: int, buffers: Dict[str, List[int]],
                    expected: Dict[str, List[int]]) -> str:
        """A self-checking Mac harness: binds the SAME body via
        mx.fast.metal_kernel, merges written masks, compares against the
        interpreter-computed expected buffers baked in here."""
        input_names = [f"{b}_in" for b in self.in_bufs] + ["lens"]
        output_names: List[str] = []
        for b in self.out_bufs:
            output_names += [f"{b}_out", f"{b}_wm"]
        lens = [len(buffers[b]) for b in self.in_bufs]
        lines = [
            "#!/usr/bin/env python3",
            f'"""Self-checking Metal harness for kernel {self.name!r},',
            "generated by metaxu emit_msl (docs/gpu_tiles.md Stage 1c).",
            "Run on a Mac with mlx installed:  python3 <this file>",
            "Exit 0 = Metal output matches the interpreter reference.",
            '"""',
            "import sys",
            "try:",
            "    import mlx.core as mx",
            "except ImportError:",
            "    print('mlx not installed (pip install mlx); this harness "
            "needs Apple silicon')",
            "    sys.exit(2)",
            "",
            "SOURCE = r'''",
            self.body,
            "'''",
            "",
            f"kernel = mx.fast.metal_kernel(",
            f"    name={self.name!r},",
            f"    input_names={input_names!r},",
            f"    output_names={output_names!r},",
            "    source=SOURCE,",
            ")",
            "",
            f"GRID_N = {grid_n}",
            f"LENS = {lens!r}",
        ]
        for b in self.in_bufs:
            lines.append(f"BUF_{b} = {buffers[b]!r}")
        for b in self.out_bufs:
            lines.append(f"EXPECTED_{b} = {expected[b]!r}")
        lines += [
            "",
            "inputs = ["
            + ", ".join(f"mx.array(BUF_{b}, dtype=mx.int64)"
                        for b in self.in_bufs)
            + ", mx.array(LENS, dtype=mx.int64)]",
            "output_shapes = []",
            "output_dtypes = []",
        ]
        for b in self.out_bufs:
            lines += [
                f"output_shapes += [(len(BUF_{b}),), (len(BUF_{b}),)]",
                "output_dtypes += [mx.int64, mx.int64]",
            ]
        lines += [
            "outs = kernel(",
            "    inputs=inputs,",
            "    grid=(GRID_N, 1, 1),",
            "    threadgroup=(min(GRID_N, 32), 1, 1),",
            "    output_shapes=output_shapes,",
            "    output_dtypes=output_dtypes,",
            "    init_value=0,",
            ")",
            "",
            "ok = True",
        ]
        for i, b in enumerate(self.out_bufs):
            lines += [
                f"out = outs[{2 * i}].tolist()",
                f"wm = outs[{2 * i + 1}].tolist()",
                f"merged = [o if m else v for o, m, v in "
                f"zip(out, wm, BUF_{b})]",
                f"if merged != EXPECTED_{b}:",
                f"    print('FAIL {b}: metal', merged, "
                f"'!= expected', EXPECTED_{b})",
                "    ok = False",
                "else:",
                f"    print('OK {b}:', merged)",
            ]
        lines += [
            "sys.exit(0 if ok else 1)",
            "",
        ]
        return "\n".join(lines)


# ---------------------------------------------------------------------------
# Emission
# ---------------------------------------------------------------------------

def emit_msl_kernel(source: str, kernel_name: str) -> MslKernel:
    """Compile ``kernel_name`` from metaxu ``source`` into an MslKernel.

    Runs the same strict front end as every backend (build context ->
    type/borrow gate -> HIR -> monomorphize -> MIR) and translates the
    kernel's MIR.  Raises MslError for anything outside the subset."""
    from .hir import HIRBuilder
    from .lower_hir_to_mir import lower_hir_to_mir
    from .monomorphize import collect_signatures, monomorphize_hir
    from .pipeline import build_context_from_source, run_pipeline_ctx

    ctx = build_context_from_source(source)
    run_pipeline_ctx(ctx)  # strict gate: production parity
    hir = HIRBuilder(ctx.tables, id_map=ctx.id_map).build(ctx.frozen_root)
    hir = monomorphize_hir(hir, collect_signatures(ctx.id_map))
    funcs = lower_hir_to_mir(hir)
    matches = [f for f in funcs if f.name == kernel_name]
    if not matches:
        near = sorted(f.name for f in funcs if kernel_name in f.name)
        raise MslError(f"kernel {kernel_name!r} not found in the module"
                       + (f" (near: {', '.join(near)})" if near else ""))
    return _emit(matches[0])


def _emit(f: MirFunc) -> MslKernel:
    if not f.blocks or not f.blocks[0].ops \
            or f.blocks[0].ops[0][0] != "params":
        raise MslError(f"kernel {f.name!r} has no parameter list")
    params = list(f.blocks[0].ops[0][1])
    if not params:
        raise MslError(f"kernel {f.name!r} takes no parameters; the first "
                       "must be the instance id `pid: int`")
    pid, bufs = params[0], params[1:]
    bufset = set(bufs)

    consts: Dict[str, int] = {}
    shapes: Dict[str, Tuple[int, int]] = {}  # tile temps -> (rows, cols)
    written: List[str] = []                  # buffers stored to, in order
    decls: Dict[str, str] = {}               # var -> C declaration

    def cint(n: str, what: str) -> int:
        if n not in consts:
            raise MslError(f"{what} must be an integer literal in kernels "
                           f"(got the computed value {n!r})")
        return consts[n]

    def shape_of(n: str, what: str) -> Tuple[int, int]:
        if n not in shapes:
            raise MslError(f"{what}: {n!r} is not a tile the emitter can "
                           "shape statically")
        return shapes[n]

    def declare(dst: str, shape: Optional[Tuple[int, int]]) -> None:
        if shape is None:
            want = "long"
        else:
            want = f"long[{shape[0] * shape[1]}]"
            if dst in shapes and shapes[dst] != shape:
                raise MslError(f"{dst!r} holds tiles of different shapes "
                               f"({shapes[dst]} vs {shape}); one shape per "
                               "variable in kernels")
            shapes[dst] = shape
        have = decls.get(dst)
        if have is None:
            decls[dst] = want
        elif have != want:
            raise MslError(f"{dst!r} is both a scalar and a tile")

    def buf_index(n: str, op: str) -> int:
        if n not in bufset:
            raise MslError(f"{op}: buffer argument {n!r} is not a kernel "
                           "buffer parameter")
        return bufs.index(n)

    # Pass 1: collect consts, shapes, declarations, written buffers, and
    # validate the subset.  Pass 2 emits, so forward-referenced facts
    # (like which buffers are written) are complete.
    for b in f.blocks:
        for op in b.ops:
            if op[0] == "params":
                continue
            if op[0] != "let" or len(op) != 4:
                raise MslError(f"kernel op {op[0]!r} is outside the MSL "
                               "subset")
            _, dst, rhs, args = op
            rk = rhs[0]
            if rk == "const":
                v = rhs[1]
                if isinstance(v, bool) or not isinstance(v, int):
                    raise MslError(
                        f"non-integer constant {v!r} in a kernel (float "
                        "kernels wait for the f32 increment; Metal has "
                        "no f64)")
                consts[dst] = v
                declare(dst, None)
            elif rk == "const_ty":
                declare(dst, None)  # unit -> 0
            elif rk == "binop":
                if rhs[1] not in _INT_BINOPS:
                    raise MslError(f"binop {rhs[1]!r} is outside the MSL "
                                   "subset")
                for a in args:
                    if a in shapes:
                        raise MslError("elementwise operators on tiles use "
                                       "Tile.add/Tile.mul in kernels")
                declare(dst, None)
            elif rk == "copy":
                src = args[0]
                if src in consts:
                    consts[dst] = consts[src]
                declare(dst, shapes.get(src))
            elif rk == "call" and len(rhs) > 1 \
                    and str(rhs[1]).startswith("Tile."):
                top = str(rhs[1])[len("Tile."):]
                if top not in _TILE_OPS:
                    hint = ""
                    if top in ("load", "store", "get", "from_vec",
                               "to_vec"):
                        hint = (" (kernels use the masked forms "
                                "Tile.load_or / Tile.store_clipped — "
                                "device code cannot raise)")
                    elif top == "zeros":
                        hint = (" (Tile.zeros builds FLOAT tiles and Metal "
                                "has no f64 — use Tile.filled(r, c, 0) in "
                                "kernels until the f32 increment)")
                    raise MslError(
                        f"Tile.{top} is outside the kernel subset{hint}")
                if top == "filled":
                    declare(dst, (cint(args[0], "Tile.filled rows"),
                                  cint(args[1], "Tile.filled cols")))
                elif top == "arange":
                    declare(dst, (cint(args[0], "Tile.arange rows"),
                                  cint(args[1], "Tile.arange cols")))
                elif top == "load_or":
                    buf_index(args[0], "Tile.load_or")
                    declare(dst, (cint(args[2], "Tile.load_or rows"),
                                  cint(args[3], "Tile.load_or cols")))
                elif top == "load_rows":
                    buf_index(args[0], "Tile.load_rows")
                    declare(dst, (cint(args[3], "Tile.load_rows rows"),
                                  cint(args[4], "Tile.load_rows cols")))
                elif top == "store_clipped":
                    bi = buf_index(args[0], "Tile.store_clipped")
                    shape_of(args[2], "Tile.store_clipped")
                    if bufs[bi] not in written:
                        written.append(bufs[bi])
                    declare(dst, None)  # unit
                elif top == "store_rows":
                    bi = buf_index(args[0], "Tile.store_rows")
                    shape_of(args[3], "Tile.store_rows")
                    if bufs[bi] not in written:
                        written.append(bufs[bi])
                    declare(dst, None)  # unit
                elif top in ("add", "mul"):
                    sa = shape_of(args[0], f"Tile.{top}")
                    sb = shape_of(args[1], f"Tile.{top}")
                    if sa != sb:
                        raise MslError(f"Tile.{top}: shape mismatch "
                                       f"{sa} vs {sb}")
                    declare(dst, sa)
                elif top == "scale":
                    declare(dst, shape_of(args[0], "Tile.scale"))
                elif top == "dot":
                    ra, ca = shape_of(args[0], "Tile.dot")
                    rb, cb = shape_of(args[1], "Tile.dot")
                    if ca != rb:
                        raise MslError(f"Tile.dot: inner dims {ca} and "
                                       f"{rb} disagree")
                    declare(dst, (ra, cb))
                elif top == "transpose":
                    r, c = shape_of(args[0], "Tile.transpose")
                    declare(dst, (c, r))
                elif top == "sum":
                    shape_of(args[0], "Tile.sum")
                    declare(dst, None)
                elif top in ("rows", "cols"):
                    r, c = shape_of(args[0], f"Tile.{top}")
                    consts[dst] = r if top == "rows" else c
                    declare(dst, None)
            else:
                what = rhs[1] if rk == "call" and len(rhs) > 1 else rk
                raise MslError(f"kernel op {what!r} is outside the MSL "
                               "subset (kernels are tile programs: tile "
                               "ops, int arithmetic and control flow)")
        t = b.term
        if t[0] not in ("br", "br_if", "ret", "unreachable"):
            raise MslError(f"terminator {t[0]!r} is outside the MSL subset")

    # Pass 2: emit the switch-machine body.
    L: List[str] = []
    L.append(f"const long {pid} = (long)thread_position_in_grid.x;")
    for name, ty in sorted(decls.items()):
        if ty == "long":
            L.append(f"long {name} = 0;")
        else:  # long[N]
            n = ty[len("long["):-1]
            L.append(f"long {name}[{n}] = {{0}};")
    L.append("int __bb = 0;")
    L.append("bool __run = true;")
    L.append("while (__run) { switch (__bb) {")

    def loop(dst: str, n: int, expr: str) -> List[str]:
        return [f"for (int __i = 0; __i < {n}; __i++) "
                f"{dst}[__i] = {expr};"]

    for bi_, b in enumerate(f.blocks):
        L.append(f"case {bi_}: {{")
        for op in b.ops:
            if op[0] == "params":
                continue
            _, dst, rhs, args = op
            rk = rhs[0]
            if rk == "const":
                L.append(f"{dst} = {rhs[1]};")
            elif rk == "const_ty":
                L.append(f"{dst} = 0;")
            elif rk == "binop":
                o = _INT_BINOPS[rhs[1]]
                if o in ("==", "!=", "<", "<=", ">", ">="):
                    L.append(f"{dst} = (long)({args[0]} {o} {args[1]});")
                else:
                    L.append(f"{dst} = {args[0]} {o} {args[1]};")
            elif rk == "copy":
                if dst in shapes:
                    r, c = shapes[dst]
                    L += loop(dst, r * c, f"{args[0]}[__i]")
                else:
                    L.append(f"{dst} = {args[0]};")
            else:  # Tile.*
                top = str(rhs[1])[len("Tile."):]
                if top == "filled":
                    r, c = shapes[dst]
                    L += loop(dst, r * c, args[2])
                elif top == "arange":
                    r, c = shapes[dst]
                    L += loop(dst, r * c, "(long)__i")
                elif top == "load_or":
                    r, c = shapes[dst]
                    bi = bufs.index(args[0])
                    L.append(f"for (int __i = 0; __i < {r * c}; __i++) {{")
                    L.append(f"  long __j = {args[1]} + __i;")
                    L.append(f"  {dst}[__i] = (__j >= 0 && __j < "
                             f"lens[{bi}]) ? {args[0]}_in[__j] : "
                             f"{args[4]};")
                    L.append("}")
                elif top == "store_clipped":
                    r, c = shapes[args[2]]
                    bi = bufs.index(args[0])
                    bn = args[0]
                    L.append(f"for (int __i = 0; __i < {r * c}; __i++) {{")
                    L.append(f"  long __j = {args[1]} + __i;")
                    L.append(f"  if (__j >= 0 && __j < lens[{bi}]) {{")
                    L.append(f"    {bn}_out[__j] = {args[2]}[__i];")
                    L.append(f"    {bn}_wm[__j] = 1;")
                    L.append("  }")
                    L.append("}")
                    L.append(f"{dst} = 0;")
                elif top == "load_rows":
                    r, c = shapes[dst]
                    bi = bufs.index(args[0])
                    L.append(f"for (int __r = 0; __r < {r}; __r++) "
                             f"for (int __c = 0; __c < {c}; __c++) {{")
                    L.append(f"  long __j = {args[1]} + __r * {args[2]} "
                             f"+ __c;")
                    L.append(f"  {dst}[__r * {c} + __c] = (__j >= 0 && "
                             f"__j < lens[{bi}]) ? {args[0]}_in[__j] : "
                             f"{args[5]};")
                    L.append("}")
                elif top == "store_rows":
                    r, c = shapes[args[3]]
                    bi = bufs.index(args[0])
                    bn = args[0]
                    L.append(f"for (int __r = 0; __r < {r}; __r++) "
                             f"for (int __c = 0; __c < {c}; __c++) {{")
                    L.append(f"  long __j = {args[1]} + __r * {args[2]} "
                             f"+ __c;")
                    L.append(f"  if (__j >= 0 && __j < lens[{bi}]) {{")
                    L.append(f"    {bn}_out[__j] = {args[3]}[__r * {c} "
                             f"+ __c];")
                    L.append(f"    {bn}_wm[__j] = 1;")
                    L.append("  }")
                    L.append("}")
                    L.append(f"{dst} = 0;")
                elif top in ("add", "mul"):
                    o = "+" if top == "add" else "*"
                    r, c = shapes[dst]
                    L += loop(dst, r * c,
                              f"{args[0]}[__i] {o} {args[1]}[__i]")
                elif top == "scale":
                    r, c = shapes[dst]
                    L += loop(dst, r * c, f"{args[0]}[__i] * {args[1]}")
                elif top == "dot":
                    ra, ca = shapes[args[0]]
                    _rb, cb = shapes[args[1]]
                    L.append(f"for (int __r = 0; __r < {ra}; __r++) "
                             f"for (int __c = 0; __c < {cb}; __c++) {{")
                    L.append("  long __acc = 0;")
                    L.append(f"  for (int __k = 0; __k < {ca}; __k++) "
                             f"__acc += {args[0]}[__r * {ca} + __k] * "
                             f"{args[1]}[__k * {cb} + __c];")
                    L.append(f"  {dst}[__r * {cb} + __c] = __acc;")
                    L.append("}")
                elif top == "sum":
                    r, c = shapes[args[0]]
                    L.append(f"{dst} = 0;")
                    L.append(f"for (int __i = 0; __i < {r * c}; __i++) "
                             f"{dst} += {args[0]}[__i];")
                elif top == "transpose":
                    r, c = shapes[args[0]]  # source shape
                    L.append(f"for (int __r = 0; __r < {r}; __r++) "
                             f"for (int __c = 0; __c < {c}; __c++) "
                             f"{dst}[__c * {r} + __r] = "
                             f"{args[0]}[__r * {c} + __c];")
                elif top in ("rows", "cols"):
                    L.append(f"{dst} = {consts[dst]};")
        t = b.term
        if t[0] == "br":
            L.append(f"__bb = {t[1]};")
        elif t[0] == "br_if":
            L.append(f"__bb = {t[1]} ? {t[2]} : {t[3]};")
        else:  # ret / unreachable
            L.append("__run = false;")
        L.append("} break;")
    L.append("} }")

    return MslKernel(name=f.name, pid_var=pid, in_bufs=bufs,
                     out_bufs=written, body="\n".join(L))
